[project]
name = "uv-python-play"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.112",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
